In [4]:
import torch

In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[ 1.8579e-14,  4.5894e-41,  1.8579e-14],
        [ 4.5894e-41,  1.8579e-14,  4.5894e-41],
        [-5.1142e+14,  3.0791e-41, -7.5102e+13],
        [ 3.0791e-41, -1.8513e+14,  3.0791e-41],
        [ 4.1411e-11,  8.1546e-33,  0.0000e+00]])


In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0412, 0.5998, 0.6943],
        [0.6560, 0.5953, 0.4818],
        [0.6855, 0.0131, 0.3768],
        [0.5791, 0.9346, 0.1384],
        [0.0339, 0.7621, 0.6216]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.zeros(5, 3, dtype=torch.float)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.5379,  0.4093,  0.9975],
        [-0.6700,  0.3226, -0.2565],
        [ 1.9604, -0.8651, -0.8148],
        [ 0.9078,  0.9250,  0.5252],
        [ 0.8431,  1.7947,  1.1176]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4360,  1.1459,  1.7456],
        [ 0.1089,  0.6936,  0.5655],
        [ 2.6958, -0.3923, -0.3804],
        [ 1.5784,  1.3588,  0.5281],
        [ 1.6961,  2.0119,  1.3094]])


In [14]:
print(torch.add(x, y))

tensor([[ 0.4360,  1.1459,  1.7456],
        [ 0.1089,  0.6936,  0.5655],
        [ 2.6958, -0.3923, -0.3804],
        [ 1.5784,  1.3588,  0.5281],
        [ 1.6961,  2.0119,  1.3094]])


In [21]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7593, 0.7616, 0.7637],
        [0.7161, 0.6888, 0.5105],
        [0.2511, 0.5725, 0.3552],
        [0.5193, 0.1543, 0.3606],
        [0.8172, 0.1725, 0.0488]])


In [26]:
print(x[:2,1:])

tensor([[0.7616, 0.7637],
        [0.6888, 0.5105]])


In [28]:
x = torch.tensor([[1, 1 ,1],[2, 2, 2],[3, 3, 3]])
print(x)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])


In [29]:
y = torch.tensor([[4, 4 ,4],[5, 5, 5],[5, 5, 5]])
print(y)

tensor([[4, 4, 4],
        [5, 5, 5],
        [5, 5, 5]])


In [30]:
print(x+y)

tensor([[5, 5, 5],
        [7, 7, 7],
        [8, 8, 8]])


In [31]:
torch.add(x,y)

tensor([[5, 5, 5],
        [7, 7, 7],
        [8, 8, 8]])

In [39]:
result = torch.empty(5, 3, dtype=torch.long)
torch.add(x, y, out=result)
print(result)

tensor([[5, 5, 5],
        [7, 7, 7],
        [8, 8, 8]])


In [40]:
y.add_(x)
print(y)

tensor([[5, 5, 5],
        [7, 7, 7],
        [8, 8, 8]])


In [41]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
